### ISSUE TITLE
Watcher breaks if there are no transactions

### ISSUE THREAD

**Issue by viktordick** [perfact/zodbsync#39]
If the undo list becomes empty due to packing the Data.FS, the watcher always records everything and then dies with the error

    Traceback (most recent call last):
      File "/usr/share/perfact/zope4/bin/zodbsync", line 6, in <module>
        perfact.zodbsync.main.run()
      File "/usr/share/perfact/zope4/lib/python3.8/site-packages/perfact/zodbsync/main.py", line 29, in run
        create_runner().run()
      File "/usr/share/perfact/zope4/lib/python3.8/site-packages/perfact/zodbsync/commands/watch.py", line 436, in run
        self._store_last_visible_txn()
      File "/usr/share/perfact/zope4/lib/python3.8/site-packages/perfact/zodbsync/commands/watch.py", line 89, in _store_last_visible_txn
        self.sync.txn_write(base64.b64encode(self.last_visible_txn))
      File "/usr/lib/python3.8/base64.py", line 58, in b64encode
        encoded = binascii.b2a_base64(s, newline=False)
    TypeError: a bytes-like object is required, not 'str'

**Comment by viktordick** [comment]
Fixed by #42
